// src/components/Login/Login.tsx
// src/pages/Login.tsx
import React, { useState } from 'react';
import { auth } from '../../firebaseConfig';
import { signInWithEmailAndPassword } from "firebase/auth";
import { useNavigate } from 'react-router-dom';

const Login: React.FC = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const handleLogin = async () => {
    try {
      await signInWithEmailAndPassword(auth, email, password);
      navigate('/notes');
    } catch (error) {
      console.error("Login error:", error);
    }
  };

  const handleSignup = async () => {
    navigate('/signup');
  };

  return (
    <div>
      <h1>Login</h1>
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      />
      <input
        type="password"
        placeholder="Password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />
      <button onClick={handleLogin}>Login</button>
      <button onClick={handleSignup}>Signup</button>
    </div>
  );
};

export default Login;

// angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  email: string = '';
  password: string = '';

  constructor(private router: Router, private authService: AuthService) {}

  async handleLogin() {
    const result = await this.authService.loginWithEmailAndPassword(this.email, this.password);
    console.log(result);
  }

  handleSignup() {
    this.router.navigate(['/signup']);
  }
}

<div class="login-container">
  <h3>Login</h3>
  <input
    type="text"
    placeholder="Email"
    [(ngModel)]="email"
  />
  <input
    type="password"
    placeholder="Password"
    [(ngModel)]="password"
  />
  <button (click)="handleLogin()">Login</button>
  <button (click)="handleSignup()">Signup</button>
</div>
