// src/components/Signup/Signup.tsx
// src/pages/Signup.tsx
import React, { useState } from 'react';
import { auth } from '../../firebaseConfig';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { useNavigate } from 'react-router-dom';

const Signup: React.FC = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  const handleSignup = async () => {
    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setError(null); // Reset error state before trying to sign up

    try {
      // Create a new user with Firebase Authentication
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      console.log("User signed up:", userCredential.user);
      navigate("/notes"); // Redirect to the notes page or wherever appropriate
    } catch (error) {
      if (error instanceof Error) {
        console.error("Signup error:", error.message);
        setError(error.message);
      } else {
        console.error("Unknown error occurred during signup");
        setError("An unknown error occurred");
      }
    }
  };

  return (
    <div>
      <h1>Sign Up</h1>
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      />
      <input
        type="password"
        placeholder="Password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />
      <input
        type="password"
        placeholder="Confirm Password"
        value={confirmPassword}
        onChange={(e) => setConfirmPassword(e.target.value)}
      />
      <button onClick={handleSignup}>Sign Up</button>
      {error && <p style={{ color: 'red' }}>{error}</p>}
    </div>
  );
};

export default Signup;

// angular/src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent {
  email: string = '';
  password: string = '';
  confirmPassword: string = '';
  error: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  async handleSignup() {
    if (this.password !== this.confirmPassword) {
      this.error = 'Passwords do not match';
    } else {
      this.error = '';
      console.log('Sign up with:', this.email, this.password);
      await this.authService.createUserWithEmailAndPassword(this.email, this.password);
    }
  }

  handleLogin() {
    this.router.navigate(['/login']);
  }
}

<div class="signup-container">
  <h3>Sign Up</h3>
  <input
    type="text"
    placeholder="Email"
    [(ngModel)]="email"
  />
  <input
    type="password"
    placeholder="Password"
    [(ngModel)]="password"
  />
  <input
    type="password"
    placeholder="Confirm Password"
    [(ngModel)]="confirmPassword"
  />
  <button (click)="handleSignup()">Sign Up</button>
  <p *ngIf="error" style="color: red;">{{ error }}</p>
  <button (click)="handleLogin()">Login</button>

</div>
